# Generated by Django 3.2 on 2022-04-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='ToDo',
        ),
    ]
